name: Code Quality

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  fail-fast: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring
          coverage: none
          tools: composer-dependency-analyser, composer-normalize, composer-require-checker, php-cs-fixer, phpstan, rector

      - name: Cache Composer dependencies
        id: cache-composer-dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-composer-${{ github.repository_id }}-${{ github.event.number }}-${{ hashFiles('**/composer.json', '**/composer.lock') }}

      - name: Add git exclusions if restoring from cache
        if: ${{ steps.cache-composer-dependencies.outputs.cache-hit == 'true' }}
        continue-on-error: true
        run: git config --global --add safe.directory '*'

      - name: Install composer dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
          php_extensions: mbstring
          version: 2
          args: --optimize-autoloader --no-progress --no-interaction 

      - name: Run Composer Dependency Analyser
        run: composer-dependency-analyser

      - name: Run Composer Require Checker
        run: composer-require-checker

      - name: Run Composer Normalize
        run: composer-normalize --dry-run --indent-size 2 --indent-style space --no-check-lock --no-update-lock

      - name: Run PHP CS Fixer
        run: php-cs-fixer check --using-cache=no --config ./vendor/kununu/scripts/src/PHP/CodeStandards/Scripts/php_cs src/ tests/

      - name: Run Rector
        run: rector process --ansi --dry-run --config rector-ci.php src/ tests/

      - name: Run PHPStan
        run: phpstan analyse --ansi
